New VSHmenu
PSP-Archive/ARK-4 pull request #155
Opened 2023-06-21 21:36 UTC by pyroesp

Improved the way the VSHMenu is displayed.
Main menu:
- fully center-justified

Advanced menu:
- menu strings with options are left-justified with their options next to it
- menu strings without are center-justified

No more need for whitespaces in the satelite files to align everything properly.
This is now done automatically.

2023-06-21 21:47 UTC, krazynez commented on extras/menus/advancedvsh/advanced.c
> +			case 0:
Looks like this was an issue before, but 0 would fall through to then be case 1, should have a break possibly.

2023-06-21 21:52 UTC, krazynez commented on extras/menus/injector/Makefile
We don't need this really.

2023-06-21 21:52 UTC, krazynez commented on extras/menus/injector/exports.exp
or this

2023-06-21 21:52 UTC, krazynez commented on extras/menus/injector/include.bak/module2.h
or this

2023-06-21 21:52 UTC, krazynez commented on extras/menus/injector/include.bak/systemctrl.h
" "

2023-06-21 21:55 UTC, krazynez commented on extras/modules/post_injector/Makefile
Not needed

2023-06-21 21:55 UTC, krazynez commented on extras/modules/post_injector/exports.exp
" "

2023-06-21 21:55 UTC, krazynez commented on extras/modules/post_injector/main.c
" '

2023-06-21 21:56 UTC, krazynez commented on loader/live/user/hello_world/main.s
Why is this here?

2023-06-21 21:57 UTC, krazynez requested changes
To many things extra added. Please just add advancedvsh, fonts, and translations.

2023-06-22 07:54 UTC, pyroesp commented
> To many things extra added. Please just add advancedvsh, fonts, and translations.

@krazynez All things indicated are from the first rebase commit on this branch, which I mentioned on discord.
No worries I'll just delete this branch, then create a new branch from main and push there.

2023-06-22 08:09 UTC, closed without merging